import os
import glob
import logging
from .base import Terminal

logger = logging.getLogger("daybreak")

# Nord Palette
PALETTES = {
    "dark": {
        "special": {
            "background": "#2e3440",
            "foreground": "#d8dee9",
            "cursor": "#d8dee9"
        },
        "colors": {
            "0": "#3b4252", "1": "#bf616a", "2": "#a3be8c", "3": "#ebcb8b",
            "4": "#81a1c1", "5": "#b48ead", "6": "#88c0d0", "7": "#e5e9f0",
            "8": "#4c566a", "9": "#bf616a", "10": "#a3be8c", "11": "#ebcb8b",
            "12": "#81a1c1", "13": "#b48ead", "14": "#88c0d0", "15": "#eceff4"
        }
    },
    "light": {
        "special": {
            "background": "#e5e9f0",
            "foreground": "#2e3440",
            "cursor": "#2e3440"
        },
        "colors": {
            "0": "#d8dee9", "1": "#bf616a", "2": "#a3be8c", "3": "#ebcb8b",
            "4": "#5e81ac", "5": "#b48ead", "6": "#88c0d0", "7": "#3b4252",
            "8": "#4c566a", "9": "#bf616a", "10": "#a3be8c", "11": "#ebcb8b",
            "12": "#5e81ac", "13": "#b48ead", "14": "#88c0d0", "15": "#2e3440"
        }
    }
}

class UniversalPty(Terminal):
    """
    Broadcasts full 16-color palette OSC escape sequences to all open PTYs.
    Using Nord palette as requested.
    """
    def set_mode(self, mode: str):
        theme = PALETTES.get(mode)
        if not theme:
            return

        sequences = []
        
        # 1. Special Colors (OSC 10, 11, 12)
        sequences.append(f"\033]10;{theme['special']['foreground']}\007")
        sequences.append(f"\033]11;{theme['special']['background']}\007")
        sequences.append(f"\033]12;{theme['special']['cursor']}\007")

        # 2. ANSI Colors 0-15 (OSC 4)
        for i, color in theme['colors'].items():
            sequences.append(f"\033]4;{i};{color}\007")

        full_payload = "".join(sequences)
        
        self._broadcast(full_payload)
        self._write_shell_script(full_payload)

    def _broadcast(self, payload):
        ptys = glob.glob("/dev/pts/[0-9]*")
        count = 0
        for pty_path in ptys:
            try:
                fd = os.open(pty_path, os.O_WRONLY | os.O_NOCTTY)
                with os.fdopen(fd, 'w') as f:
                    f.write(payload)
                count += 1
            except (PermissionError, OSError):
                pass 
        
        if count > 0:
            logger.info(f"Broadcasted Nord palette to {count} terminals.")

    def _write_shell_script(self, payload):
        config_dir = os.path.expanduser("~/.config/daybreak")
        os.makedirs(config_dir, exist_ok=True)
        script_path = os.path.join(config_dir, "theme.sh")
        
        try:
            with open(script_path, "w") as f:
                f.write(f"#!/bin/sh\n")
                f.write(f"# Auto-generated by Daybreak.\n")
                f.write(f"printf '{payload}'\n")
        except Exception as e:
            logger.warning(f"Failed to write persistence script: {e}")
