import os
import logging
from pathlib import Path
from .base import Terminal

logger = logging.getLogger("daybreak")

class Neovim(Terminal):
    """
    Manages Neovim theme by writing a shared configuration file (Lua).
    Neovim instances can source this file or use a helper plugin to watch it.
    """
    def __init__(self):
        self.config_dir = Path(os.path.expanduser("~/.config/daybreak"))
        self.theme_file = self.config_dir / "theme.lua"

    def set_mode(self, mode: str):
        self.config_dir.mkdir(parents=True, exist_ok=True)
        
        bg = "dark" if mode == "dark" else "light"
        
        # Content to be sourced by Neovim
        lua_content = f"""-- Auto-generated by Daybreak
vim.o.background = "{bg}"
-- You can add your own logic here or rely on the background change
"""
        try:
            with open(self.theme_file, "w") as f:
                f.write(lua_content)
            logger.info(f"Updated Neovim config at {self.theme_file}")
            
            # Optional: Signal Neovim instances to reload if they are configured to listen for signals
            # But the user asked for a "pull" model via a plugin, so we primarily rely on the file.
            # However, we can generate a helper plugin file for the user to use.
            self._generate_helper_plugin()
            
        except Exception as e:
            logger.error(f"Failed to update Neovim config: {e}")

    def _generate_helper_plugin(self):
        """
        Generates a small Lua module that users can require in their init.lua
        to automatically pull the theme.
        """
        plugin_path = self.config_dir / "nvim_watcher.lua"
        
        # This plugin sets up an autocommand to reload the theme on FocusGained
        # or provides a command to reload it manually.
        plugin_content = f"""-- Daybreak Neovim Helper
-- Add this to your init.lua: dofile(os.getenv("HOME") .. "/.config/daybreak/nvim_watcher.lua")

local theme_file = "{self.theme_file}"

local function load_daybreak_theme()
  local f = io.open(theme_file, "r")
  if f then
    f:close()
    dofile(theme_file)
  end
end

-- Load on startup
load_daybreak_theme()

-- Reload on FocusGained (when you switch back to the terminal)
local group = vim.api.nvim_create_augroup("DaybreakTheme", {{ clear = true }})
vim.api.nvim_create_autocmd("FocusGained", {{
  group = group,
  callback = load_daybreak_theme
}})

-- User command to manual reload
vim.api.nvim_create_user_command("DaybreakReload", load_daybreak_theme, {{}})
"""
        try:
            with open(plugin_path, "w") as f:
                f.write(plugin_content)
        except Exception as e:
            logger.warning(f"Failed to generate Neovim helper plugin: {e}")