import * as fs from 'fs';
import * as path from 'path';
import { config } from '../config';
import { Terminal } from './base';

const logger = {
  info: (m: string) => {},
  warn: (m: string) => console.warn('[daybreak]', m),
  error: (m: string) => console.error('[daybreak]', m),
};

export class Neovim extends Terminal {
  private configDir: string;
  private themeFile: string;
  private watcherFile: string;
  private bootstrapFile: string;

  constructor(configDir?: string) {
    super();
    this.configDir = configDir || config.configDir;
    this.themeFile = path.join(this.configDir, 'theme.lua');
    this.watcherFile = path.join(this.configDir, 'nvim_watcher.lua');
    this.bootstrapFile = path.join(this.configDir, 'nvim_bootstrap.lua');
  }

  setMode(mode: string): void {
    fs.mkdirSync(this.configDir, { recursive: true });

    const bg = mode === 'dark' ? 'dark' : 'light';
    const targetScheme = config.get(
      'integrations',
      `neovim_${bg}_scheme`,
      bg === 'dark' ? 'tokyonight' : 'tokyonight-day',
    );
    const luaScheme = Neovim.toLuaString(targetScheme);

    const luaContent = `-- Auto-generated by Daybreak
vim.g.daybreak_mode = "${bg}"
vim.g.daybreak_target_colorscheme = "${luaScheme}"
vim.o.background = "${bg}"

if vim.g.daybreak_target_colorscheme and #vim.g.daybreak_target_colorscheme > 0 then
  local ok = pcall(vim.cmd.colorscheme, vim.g.daybreak_target_colorscheme)
  if not ok and vim.g.colors_name and #vim.g.colors_name > 0 then
    pcall(vim.cmd.colorscheme, vim.g.colors_name)
  end
elseif vim.g.colors_name and #vim.g.colors_name > 0 then
  pcall(vim.cmd.colorscheme, vim.g.colors_name)
end

pcall(vim.api.nvim_exec_autocmds, "User", { pattern = "DaybreakThemeChanged" })
`;

    try {
      fs.writeFileSync(this.themeFile, luaContent);

      if (!fs.existsSync(this.watcherFile)) {
        this._generateHelperPlugin();
      }
      if (!fs.existsSync(this.bootstrapFile)) {
        this._generateBootstrapPlugin();
      }
    } catch (e) {
      logger.error(`Failed to update Neovim config: ${e}`);
    }
  }

  generateStaticFiles(): void {
    fs.mkdirSync(this.configDir, { recursive: true });
    this._generateHelperPlugin();
    this._generateBootstrapPlugin();
  }

  private _generateHelperPlugin(): void {
    const content = `-- Daybreak Neovim Helper

if vim.g.daybreak_nvim_watcher_loaded then
  return
end
vim.g.daybreak_nvim_watcher_loaded = true

local theme_file = [=[${this.themeFile}]=]
local uv = vim.uv or vim.loop
local fs_watcher
local debounce_timer

local function load_daybreak_theme()
  local f = io.open(theme_file, "r")
  if f then
    f:close()
    local ok, err = pcall(dofile, theme_file)
    if not ok then
      vim.schedule(function()
        vim.notify("Daybreak: failed to load theme.lua: " .. tostring(err), vim.log.levels.WARN)
      end)
    end
  end
end

local function schedule_reload()
  if not uv then
    load_daybreak_theme()
    return
  end

  if not debounce_timer then
    debounce_timer = uv.new_timer()
  end
  if not debounce_timer then
    load_daybreak_theme()
    return
  end

  debounce_timer:stop()
  debounce_timer:start(120, 0, vim.schedule_wrap(load_daybreak_theme))
end

local group = vim.api.nvim_create_augroup("DaybreakTheme", { clear = true })
vim.api.nvim_create_autocmd({"FocusGained", "BufEnter"}, {
  group = group,
  callback = load_daybreak_theme,
})

if uv and uv.new_fs_event then
  fs_watcher = uv.new_fs_event()
  if fs_watcher then
    local ok = pcall(function()
      fs_watcher:start(theme_file, {}, function()
        schedule_reload()
      end)
    end)
    if not ok then
      fs_watcher = nil
    end
  end
end

vim.api.nvim_create_autocmd("VimLeavePre", {
  group = group,
  callback = function()
    if fs_watcher then
      pcall(fs_watcher.stop, fs_watcher)
      pcall(fs_watcher.close, fs_watcher)
      fs_watcher = nil
    end
    if debounce_timer then
      pcall(debounce_timer.stop, debounce_timer)
      pcall(debounce_timer.close, debounce_timer)
      debounce_timer = nil
    end
  end
})

vim.api.nvim_create_user_command("DaybreakReload", load_daybreak_theme, { force = true })
load_daybreak_theme()
`;
    try {
      fs.writeFileSync(this.watcherFile, content);
    } catch (e) {
      logger.warn(`Failed to generate Neovim helper plugin: ${e}`);
    }
  }

  private _generateBootstrapPlugin(): void {
    const themePath = `[=[${this.themeFile}]=]`;
    const watcherPath = `[=[${this.watcherFile}]=]`;
    const configFilePath = `[=[${path.join(this.configDir, 'config.toml')}]=]`;

    const content = `-- Daybreak Neovim Bootstrap
-- Add this to init.lua (ideally before plugin setup):
-- dofile(vim.fn.expand("~/.config/daybreak/nvim_bootstrap.lua"))

if vim.g.daybreak_nvim_bootstrap_loaded then
  return _G.DaybreakNvim
end
vim.g.daybreak_nvim_bootstrap_loaded = true

local M = {}
local theme_file = ${themePath}
local watcher_file = ${watcherPath}
local config_file = ${configFilePath}

local function read_file(path)
  local f = io.open(path, "r")
  if not f then
    return nil
  end
  local content = f:read("*a")
  f:close()
  return content
end

local function write_file(path, content)
  local f = io.open(path, "w")
  if not f then
    return false
  end
  f:write(content)
  f:close()
  return true
end

local function esc_toml(text)
  return (tostring(text):gsub("\\\\", "\\\\\\\\"):gsub('"', '\\\\\\"'))
end

local function resolve_mode(mode)
  if mode == "light" or mode == "dark" then
    return mode
  end
  local gmode = vim.g.daybreak_mode
  if gmode == "light" or gmode == "dark" then
    return gmode
  end
  local bg = vim.o.background
  if bg == "light" or bg == "dark" then
    return bg
  end
  return nil
end

local function upsert_integrations(content, key, value)
  local lines = vim.split(content, "\\n", { plain = true })
  local out = {}
  local values = {}
  local order = {}
  local seen = {}
  local insert_at = nil
  local in_integrations = false

  local function set_value(k, v)
    if not k or k == "" or not v or v == "" then
      return
    end
    if seen[k] then
      for i, existing in ipairs(order) do
        if existing == k then
          table.remove(order, i)
          break
        end
      end
    end
    values[k] = v
    seen[k] = true
    table.insert(order, k)
  end

  for _, line in ipairs(lines) do
    local section = line:match("^%s*%[([^%]]+)%]%s*$")
    if section then
      if section == "integrations" then
        in_integrations = true
        if not insert_at then
          insert_at = #out + 1
        end
      else
        in_integrations = false
        table.insert(out, line)
      end
    else
      if in_integrations then
        local k, v = line:match("^%s*([%w_%-]+)%s*=%s*(.-)%s*$")
        if k and v then
          set_value(k, v)
        end
      else
        table.insert(out, line)
      end
    end
  end

  if not insert_at then
    insert_at = #out + 1
  end

  set_value(key, value)

  local block = {}
  if insert_at > 1 and out[insert_at - 1] ~= "" then
    table.insert(block, "")
  end
  table.insert(block, "[integrations]")
  for _, k in ipairs(order) do
    table.insert(block, k .. " = " .. values[k])
  end
  if insert_at <= #out and out[insert_at] ~= "" then
    table.insert(block, "")
  end

  for i = #block, 1, -1 do
    table.insert(out, insert_at, block[i])
  end

  return table.concat(out, "\\n")
end

local function set_neovim_scheme(mode, scheme)
  mode = resolve_mode(mode)
  if mode ~= "light" and mode ~= "dark" then
    return
  end
  if type(scheme) ~= "string" or scheme == "" then
    return
  end
  local content = read_file(config_file)
  if not content then
    return
  end
  local key = mode == "light" and "neovim_light_scheme" or "neovim_dark_scheme"
  local rhs = '"' .. esc_toml(scheme) .. '"'
  local updated = upsert_integrations(content, key, rhs)
  write_file(config_file, updated)
end

function M.load_theme()
  local ok, err = pcall(dofile, theme_file)
  if not ok then
    vim.schedule(function()
      vim.notify("Daybreak: failed to load theme.lua: " .. tostring(err), vim.log.levels.WARN)
    end)
  end
end

function M.load_watcher()
  local ok, err = pcall(dofile, watcher_file)
  if not ok then
    vim.schedule(function()
      vim.notify("Daybreak: failed to load watcher: " .. tostring(err), vim.log.levels.WARN)
    end)
  end
end

function M.apply_target_scheme()
  local scheme = vim.g.daybreak_target_colorscheme
  if type(scheme) == "string" and scheme ~= "" then
    pcall(vim.cmd.colorscheme, scheme)
  end
end

function M.get_target_colorscheme()
  return vim.g.daybreak_target_colorscheme
end

function M.toggle_daybreak()
  local cmd = { "daybreak", "toggle" }

  local function notify_success(stdout)
    local out = (stdout or ""):gsub("%s+$", "")
    vim.schedule(function()
      if out ~= "" then
        vim.notify("Daybreak toggled: " .. out, vim.log.levels.INFO)
      else
        vim.notify("Daybreak toggled.", vim.log.levels.INFO)
      end
    end)
  end

  local function notify_failure(message)
    local msg = (message or ""):gsub("%s+$", "")
    if msg == "" then
      msg = "daybreak toggle failed"
    end
    vim.schedule(function()
      vim.notify("Daybreak toggle failed: " .. msg, vim.log.levels.WARN)
    end)
  end

  if vim.system then
    vim.system(cmd, { text = true }, function(result)
      if result.code == 0 then
        notify_success(result.stdout)
      else
        notify_failure(result.stderr or result.stdout or ("exit " .. tostring(result.code)))
      end
    end)
    return
  end

  local stdout_chunks = {}
  local stderr_chunks = {}
  local job_id = vim.fn.jobstart(cmd, {
    stdout_buffered = true,
    stderr_buffered = true,
    on_stdout = function(_, data)
      if type(data) == "table" and #data > 0 then
        table.insert(stdout_chunks, table.concat(data, "\\n"))
      end
    end,
    on_stderr = function(_, data)
      if type(data) == "table" and #data > 0 then
        table.insert(stderr_chunks, table.concat(data, "\\n"))
      end
    end,
    on_exit = function(_, code)
      if code == 0 then
        notify_success(table.concat(stdout_chunks, "\\n"))
      else
        notify_failure(table.concat(stderr_chunks, "\\n"))
      end
    end,
  })

  if job_id <= 0 then
    notify_failure("failed to start daybreak toggle")
  end
end

local group = vim.api.nvim_create_augroup("DaybreakBootstrap", { clear = true })
vim.api.nvim_create_autocmd("User", {
  group = group,
  pattern = "DaybreakThemeChanged",
  callback = M.apply_target_scheme,
})

vim.api.nvim_create_autocmd("ColorScheme", {
  group = group,
  callback = function()
    set_neovim_scheme(vim.g.daybreak_mode, vim.g.colors_name)
  end,
})

vim.api.nvim_create_user_command("DaybreakToggle", M.toggle_daybreak, { force = true })

M.load_watcher()

_G.DaybreakNvim = M
return M
`;
    try {
      fs.writeFileSync(this.bootstrapFile, content);
    } catch (e) {
      logger.warn(`Failed to generate Neovim bootstrap plugin: ${e}`);
    }
  }

  static toLuaString(value: string): string {
    return String(value || '').replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  }

  static toLuaBracketString(value: string): string {
    return `[=[${String(value || '')}]=]`;
  }
}
